matomo-org/tag-manager

Template/Trigger/ScrollReachTrigger.web.js
Not sure if the PR is 100% needed but maybe there could be some race conditions with the scroll event being triggered again while just evaluating this (eg on a slow laptop).
=> Ensure scroll reach trigger is only executed once even if there are race conditions

Template/Tag/FacebookPixelTag.php, Template/Tag/FacebookPixelTag.web.js, images/icons/F_icon.svg
Attempting to create an interface for adding Facebook Pixels Tags. Based on default Google Analytics tag and proposed Google AdWords Tag. 
Note: Tested on a live server and it doesn’t appear to add the section of Tags available? I know this product is new so documentation is light but I’m wondering if there is a missing ingredient for it to show up?
Disclaimer: "Facebook" is a registered trademark of Facebook, Inc. I am not officially partnered with, authorized, endorsed, or sponsored by Facebook. I believe this falls under “General” acceptable use as defined in [Facebook Brand Guidelines](https://en.facebookbrand.com/guidelines/brand) but I’m happy to remove/modify if not.
=> Add Facebook Pixel Tag Type to Matomo Tag Manager

README.md
`poser.pugx.org` only seems to work with packagist packages, so it doesn't make sense to link it.
PS: We should maybe link to https://plugins.matomo.org/TagManager in the header.
=> remove license badge from readme

Context/Storage/Filesystem.php
The directory might not exist if a custom directory is configured.
=> Create directory if it doesn't exist yet when writing container

TagManager.php, Template/Tag/MatomoTag.php, Template/Tag/MatomoTag.web.js, Template/Variable/MatomoConfigurationVariable.php, tests/Integration/Template/Tag/MatomoTagTest.php, tests/System/expected/test___TagManager.exportContainerVersion_site_default_container.xml, tests/System/expected/test_webContext__TagManager.getAvailableVariableTypesInContext.xml
This way the Matomo tracker will be loaded faster, and reduces the load on the server as only one file needs to be served on each request instead of two.
fix https://github.com/matomo-org/tag-manager/issues/2
=> Add option to bundle Matomo in container directly

Template/Tag/MatomoTag.php, Template/Tag/MatomoTag.web.js
We've seen a container where for some reason the tracker was supposed to be bundled, but wasn't. I cannot reproduce it, but think this should fix the issue.
=> Make sure that if JS tracker doesnt get bundled the tracking still works

TagManager.php
See the comment
// tag manager was likely activated in this request because the DI config could not be resolved.
// this happens eg when calling "plugin:activate TagManager AnotherPluginName".
// in this case tag manager gets installed and activated, and then during the same request, when
// AnotherPluginName is being installed, it will go into this method because we listen to plugin
// change events and component change events. It will then try to get the container but it fails
// because at the beginning of the request, the TagManager was not yet activated and therefore the
// TagManager/config/config.php was not loaded. In this case we skip generating containers as it would fail
// and a container would not yet exist anyway.
=> Improve TagManager plugin activation behaviour

README.md
I presume now that we ship it directly in core with Matomo we no longer mark it as beta :) cc @mattab
=> Tag Manager out of beta

Activity/BaseActivity.php, Activity/TagAdded.php, Activity/TagDeleted.php, Activity/TagUpdated.php, Activity/TriggerAdded.php, Activity/TriggerDeleted.php, Activity/TriggerUpdated.php, Activity/VariableAdded.php, Activity/VariableDeleted.php, Activity/VariableUpdated.php
Otherwise, when publishing for example a container, it will create lots of Add tags, triggers, variables activities.
=> Trigger activity only if that api was called directly

Template/Variable/MatomoConfigurationVariable.php, tests/System/expected/test_webContext__TagManager.getAvailableVariableTypesInContext.xml
fix https://github.com/matomo-org/tag-manager/issues/133
Also no longer validate the idSite if matomo URL is pointing to a different matomo instance since the idSite might exist on another instance.
=> Ensure matomo idSite can be assigned a variable

TagManager.php
Fixes if 2FA is forced for everyone, it would potentially render the 2FA setup or the 2FA code prompt instead of the debug frame.
We can safely ignore it here as it is called mainly by `doAsSuperUser` and it is a fixed script that is same for everyone with no variables or anything. (it could be basically as well available for anonymous).
=> The tag manager debug screen should not require 2FA

Template/Tag/MatomoTag.web.js, Template/Variable/MatomoConfigurationVariable.php, tests/System/expected/test___TagManager.exportContainerVersion_site_default_container.xml, tests/System/expected/test_webContext__TagManager.getAvailableVariableTypesInContext.xml
This PR brings couple improvements
* Before if someone used a Matomo Tag in the container, the Matomo tracking code was always loaded no matter if the tag was fired or not
* Now at least the first tracker will be initialized as part of `window.piwikPluginAsyncInit` as recommended fixing some compatibility issues with custom Matomo tracker plugins at least for the first Matomo tag (when not bundled may also fix it for other matomo tags depending how long it takes to load the tracker file)
* Support send beacon
=> Load matomo tracker only when the tracker is fired

Context/BaseContext/TemplateLocator.php, tests/Integration/Context/BaseContext/TemplateLocatorTest.php
refs https://github.com/matomo-org/tag-manager/issues/148
Not the best fix but only thing I can think of without needing to use `eval`
=> Fix JS Function Variable needs to generate one template per variable

Template/Tag/MatomoTag.web.js
Steps to reproduce:
* Create a Matomo tag on a container, configured with cookie domain `.example.com`
* Load the website www.example.com
* Got: Two cookies are created on domains .example.com and www.example.com eg.
```
9b1feac345884afb.1553796770.0.1553796834.. on domaine www.example.com
97b1f55eea218e3e.1553796770.1.1553796834.1553796770. on .example.com
```
* Expected only one cookie on .example.com
Looked a bit into it and found that:
* in the container it calls `        tracker = Piwik.addTracker(trackerUrl, matomoConfig.idSite);`
* which then triggers the line `setVisitorIdCookie();` in the Tracker constructor
* which creates the wrong cookie on `www.example.com`
* the wrong cookie is created because at this point, the function `setCookieDomains` hasn't been called yet. It's called …
=> Matomo Tag: set the id site later so that cookies are created correctly

angularjs/manageVersion/edit.controller.js
As discussed, we keep it super simple and only suggest a version number if last version was an integer/number. We don't increase for now versions like `v5` or `5.4.1` (we wouldn't know if it's a minor/major/patch release etc)
fix #115
=> Automatically prefill version number if last version was integer

Model/Container.php, angularjs/manageVersion/edit.controller.js
refs https://forum.matomo.org/t/tag-manager-all-tags-deleted-during-version-creation/33548
I doubt it fixes anything though because if creating a new version failed, it would return an API error.
=> Check container version exists before publishing it

Template/Tag/CustomHtmlTag.web.js
When Custom HTML tag is set to be inserted into the body, but the tag manager is embedded in the script header and loaded and executed before the body is present in the dom, we need to wait for the body to become available.
=> Prevent error "cannot read property 'firstChild' of null"

Model/Tag.php
When we do a tag update startDate and endDate is submitted as a empty
string that is converted to 0000-00-00 00:00:00 on database. That
conversion cause an ExceptionInvalidDateBeforeFirstWebsite exception
when We try to update tags again or publish a new version broken the
whole tagmanager plugin
=> fix: Tag::updateContainerTag setting a wrong startDate and endDate value

Dao/TagsDao.php
Noticed some DBs return `0000-00-00 00:00:00` depending on sql mode.
=> Convert empty date to null

Template/Variable/MatomoConfigurationVariable.php, tests/System/expected/test___TagManager.exportContainerVersion_site_default_container.xml, tests/System/expected/test_webContext__TagManager.getAvailableVariableTypesInContext.xml
For newer installations we want to use by default matomo.js and matomo.php instead of piwik.js and piwik.php
=> Use matomo.js and matomo.php as default if preferred

TagManager.php
Not sure why I added it there considering they are being regenerated in a task every hour or so anyway.
=> Do not regenerate containers after core archiving

Template/Tag/MatomoTag.web.js
When the tracker js is already loaded before the container loads, the first trigger callback will not get called because libAvailable = false when inserting the callback.
This commit fixes this problem.
=> Fix first trigger callback when tracker js is already loaded

Template/Tag/MatomoTag.web.js, Template/Variable/MatomoConfigurationVariable.php, tests/System/expected/test___TagManager.exportContainerVersion_site_default_container.xml, tests/System/expected/test_webContext__TagManager.getAvailableVariableTypesInContext.xml
* Added new setting "Use external Tracker" that allows to use a Matomo JS Tracker that is already loaded by the website by other means (for example the classic Matomo JS tracking code)
* Replaced Piwk.addTracker() with Piwik.getTracker(); this fixes using Matomo Tag Manager together with classic Matomo Code. addTracker() does some caching and did not work in my tests. getTracker() always creates a new Piwik instance, but since the Tag Manage code already caches the Piwik Instance this should be no problem
=> Adjustments for using TM and classic Tracking Code at the same time

TagManager.php
Make sure container generation is execute in the context of the configured site
@makarovstas I can't really think how this can happen except if the site was created through CLI or so. But even then I can't really think yet how this could happen. Could you try and test this change if this fixe the issue for you?
fix #203
=> Fix idsite may be 0 in the container under circumstances
