README.md
=> Mention more details on the readme

lang/en.json, tests/Integration/Model/EnvironmentTest.php, tests/Integration/SystemSettingTest.php
Just a small wording improvement
=> improve wording

lang/en.json, tests/System/expected/test_webContext__TagManager.getAvailableTriggerTypesInContext.xml
fixes #63 
Do Transifex translations automatically get reset when the source changes?
=> fix wording

Template/Tag/AddThisTag.php, Template/Tag/AddThisTag.web.js, images/icons/addthis.svg, lang/en.json
Pretty similar to the Shareaholic #48 tag.
A bit more simple as everything get's configured via the web dashboard.
=> add basic AddThis tag

CHANGELOG.md, Menu.php, plugin.json
=> Link to Manage Tags page in top menu when user has only view access

Template/Trigger/AllLinksClickTrigger.web.js, tests/javascript/index.php
=> Fix all links trigger doesn't work when clicking on element within link

angularjs/manageTrigger/edit.controller.js
=> Update button disabled if you remove a condition from a trigger

lang/en.json
refs https://github.com/matomo-org/tag-manager/pull/78
=> Fix typo in custom template settings

Template/Trigger/FormSubmitTrigger.web.js, Template/Variable/PreConfigured/FormElement.php, lang/en.json, tests/System/expected/test_no_content__TagManager.getAvailableContainerVariables.xml, tests/System/expected/test_with_content__TagManager.getAvailableContainerVariables.xml, tests/UI/expected-screenshots/ContainerVariable_variable_some_exist.png, tests/javascript/index.php
=> Support form element

angularjs/manageTag/edit.controller.js
fix https://github.com/matomo-org/tag-manager/issues/105
=> Enable update button when removing a block trigger

Dao/TagsDao.php, Dao/TriggersDao.php, Dao/VariablesDao.php, tests/Integration/Dao/TagsDaoTest.php, tests/Integration/Dao/TriggersDaoTest.php, tests/Integration/Dao/VariablesDaoTest.php, tests/Integration/Model/TagTest.php, tests/Integration/Model/TriggerTest.php, tests/Integration/Model/VariableTest.php
=> fix changing name of variable causes removing trigger in a tag

Template/Tag/MatomoTag.web.js, Template/Variable/MatomoConfigurationVariable.php
=> Allow users to configure set secure cookie

Template/Tag/MatomoTag.php
fix https://github.com/matomo-org/matomo/issues/13761
=> Make sure event value can accept variables and numbers

Template/Tag/MatomoTag.php, Template/Tag/MatomoTag.web.js
fix #122 
@mattab can you give this a try?
=> Support custom title and url for pageviews

javascripts/tagmanager.js, tests/javascript/index.php
see https://forum.matomo.org/t/trigger-for-variable-greater-then-equals-1-doesnt-fire/31458?u=lukas
=> Fix greater than comparison is not working

Template/Tag/MatomoTag.php
Small PR for https://github.com/matomo-org/tag-manager/issues/156
=> MatomoTag: fix loadTemplate piwik fallback

lang/en.json
=> Fix incorrect writing of Piwik

angularjs/importVersion/import-version.directive.html, angularjs/manageContainer/edit.directive.html, angularjs/manageTag/edit.directive.html, angularjs/manageTrigger/edit.directive.html, angularjs/manageVariable/edit.directive.html, angularjs/manageVersion/edit.directive.html, angularjs/tagmanagerTrackingCode/tagmanager.directive.html
refs https://github.com/matomo-org/matomo/issues/13826
=> improves IE11 support

config/tracker.php
=> Ensure plugin has a tracker.php file

Template/Tag/MatomoTag.web.js, Template/Variable/MatomoConfigurationVariable.php, tests/System/expected/test___TagManager.exportContainerVersion_site_default_container.xml, tests/System/expected/test_webContext__TagManager.getAvailableVariableTypesInContext.xml
Added support for js/ and js/tracker.php endpoints.
=> Added settings to configure piwik.js and piwik.php path

Template/Tag/MatomoTag.web.js, Template/Variable/MatomoConfigurationVariable.php, tests/System/expected/test___TagManager.exportContainerVersion_site_default_container.xml, tests/System/expected/test_webContext__TagManager.getAvailableVariableTypesInContext.xml
This setting allows to configure the setDomains() call. Related: https://github.com/matomo-org/tag-manager/issues/160
=> Added a config setting for "setDomains"

Template/Tag/MatomoTag.web.js
fix https://github.com/matomo-org/tag-manager/issues/205
=> Fix JS error when domains are set

Template/Tag/EtrackerTag.web.js
Custom dimensions were not set up correctly.
=> Update of EtrackerTag.web.js
